### ISSUE TITLE
picker directory missing from wheel pypi distribution

### ISSUE THREAD

**Issue by ddmee** [gtalarico/pipenv-pipes#9]
* Pipenv Pipes version: pipenv_pipes-0.5.0-py2.py3-none-any.whl (8.4 kB)
* Python version: python3.6
* Operating System: linux, ubuntu

### Description
Can't run pipes because of an import error.

I installed pipenv_pipes from with pip. Using the command:

`$ pip3 install pipenv-pipes --user`

When I run pipes, the package can't import picker. This is because the installation has no picker subdirectory. I looked at the .whl and there is no picker included in the .whl. I think something in the build process must have skipped this directory.

### Output showing problem
```
$pipes

Traceback (most recent call last):
  File "/home/me/.local/bin/pipes", line 7, in <module>
    from pipenv_pipes.cli import pipes
  File "/home/me/.local/lib/python3.5/site-packages/pipenv_pipes/cli.py", line 10, in <module>
    from .picker import Picker
ImportError: No module named 'pipenv_pipes.picker'

```

So  looking at the sitepackage directory, there is no picker subdir

```
$cd .local/lib/python3.5/site-packages/pipenv_pipes/
$cd ls
cli.py  core.py  environment.py  __init__.py  pipenv.py  __pycache__/  utils.py

```
Having a look at the contents of .whl, picker is missing:

```
$pwd
/pipenv_pipes-0.5.0-py2.py3-none-any.whl_FILES
$ls pipenv_pipes/
cli.py  core.py  environment.py  __init__.py  pipenv.py  utils.py
```

**Comment by ddmee** [comment]
Thanks @gtalarico. The issue is now fixed. I've got pipes running on windows. Had to install the curses wheel per the instructions, but so far, so good. Cheers.
